---
- name: setup common configuration
  hosts: localhost
  connection: local
  become: true
  become_method: su
  tasks:
    - name: yum updates
      include_tasks: yum.yml

    - name: sshd config
      include_tasks: sshd.yml

    - name: sudo config
      include_tasks: sudo.yml

    - name: virt setup
      include_tasks: virt.yml

    - name: home dir setup
      include_tasks:
        file: home.yml
        apply:
          become: no

    - name: root setup
      include_tasks: root.yml

    #  roles:
    #    - unifi
