# Yes, we should add the free repo too... but then I'd just disable all the
# packages below.
- name: Setup rpmfusion repo
  yum:
    name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm, https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm
    state: present

- name: Enable supplementary for RHEL
  rhsm_repository:
    name: rhel-{{ ansible_distribution_major_version }}-server-optional-rpms
    state: enabled
  when: ansible_distribution == "RedHat"


# TODO: restrict to just unifi packages, as rpmfusion isn't completely safe
- name: Restrict rpmfusion to only unifi packages
  lineinfile:
    path: /etc/yum.repos.d/rpmfusion-nonfree-updates.repo
    regexp: '^includepkgs\s*='
    line: 'includepkgs=unifi*'

- name: Install unifi packages
  yum:
    name: unifi-data, unifi
    state: latest

- name: Add service port to firewall
  firewalld:
    immediate: yes
    permanent: yes
    port: 8080/tcp
    state: enabled

- name: Add webui port to firewall
  firewalld:
    immediate: yes
    permanent: yes
    port: 8443/tcp
    state: enabled

- name: Start unifi services
  service:
    name: unifi
    enabled: yes
    state: started
