- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have sudo access
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL)'
    validate: 'visudo -cf %s'

- name: Add user to wheel group
  user:
    name: "{{ user_id }}"
    groups: wheel
    append: yes
